[colors.bright]
black = "#333333"
blue = "#cccccc"
cyan = "#aaaaaa"
green = "#aaaaaa"
magenta = "#f752c0"
red = "#888888"
white = "#ffffff"
yellow = "#bbbbbb"

[colors.normal]
black = "#111111"
blue = "#e35420"
cyan = "#aaaaaa"
green = "#f752c0"
magenta = "#f752c0"
red = "#666666"
white = "#ffffff"
yellow = "#aaaaaa"

[colors.primary]
background = "#111111"
foreground = "#aaaaaa"

[colors.search.focused_match]
background = "#34e0c1"
foreground = "#000000"

[colors.search.matches]
background = "#f752cb"
foreground = "#000000"

[colors.selection]
background = "#f752cb"
text = "#000000"

[font]
size=7
#size = 12
#size = 10

[font.normal]
family = "Jetbrains Mono"
style = "regular"

[window.padding]
x = 15
y = 15
